version: '3'

services:
  ballot-redis-test:
    image: "redis:alpine"
    container_name:
      ballot_test_redis
    ports:
      - 6381:6379
    networks:
      - db

networks:
  db:
    driver: bridge
