version: '3'

networks:
  dev-net:
    driver: bridge

services:
  redis_dev:
    image: "redis:alpine"
    container_name:
      ballot_dev_redis
    ports:
      - 6380:6379
    networks:
      - dev-net

  redis_test:
    image: "redis:alpine"
    container_name:
      ballot_test_redis
    ports:
      - 6381:6379
    networks:
      - dev-net
