version: '3'

networks:
  ballot-dev-net:
    driver: bridge

services:
  dev_redis:
    image: "redis:alpine"
    container_name:
      dev_redis
    ports:
      - 6380:6379
    networks:
      - ballot-dev-net

  test_redis:
    image: "redis:alpine"
    container_name:
      test_redis
    ports:
      - 6381:6379
    networks:
      - ballot-dev-net
