name: Publish Docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: papito/ballot
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: JWT Generator
        id: jwtGenerator
        uses: morzzz007/github-actions-jwt-generator@1.0.1
        with:
          secret: ${{ secrets.DEPLOY_SECRET }}
          payload: '{"app": "ballot"}'
      - name:  Deploy
        run:
          "curl -v POST -H \"Content-Type: application/json\"  -H \"Authorization: Bearer ${{steps.jwtGenerator.outputs.token}}\"  ${{ secrets.DEPLOY_URL }} -d '{}'"
